### ISSUE TITLE
minor installation annoyances

### ISSUE THREAD

**Issue by pattonw** [funkelab/lsd#10]
It would be nice to have an installation guide. pip installing usually fails for me and then once installed it usually doesn't work immediately.
Here are the issues I usually run into:

- `pip install git+git://github.com/funkelab/lsd.git` usually fails with a "ModuleNotFoundError: No module named 'Cython'"
  - solvable with pyproject.toml.
- After installation trying to import lsd throws errors until some extra packages are installed.
  - packages:
    - mahotas
    - matplotlib
    - git+git://github.com/funkelab/funlib.segment.git (this one specifically is annoying since it requires boost to install. I don't need it if I just want the lsd gunpowder node)
    - daisy
    - git+git://github.com/funkey/waterz.git
  - This isn't as problematic as the cython issue, but some of these seem like they aren't strictly necessary, especially if you only want to quickly compute some lsds on an in-memory dataset.
- Finally, pip install from the repo can be a bit slow since there is a 19MB model checkpoint in the notebook tutorials, 23MB in `.git/objects/pack`, Not sure what that is.
  - distributing on pypi would probably be the best solution here so the model could stay in the notebooks. unfortunately it seems someone already took the name `lsd`.
  - alternatively moving the model to a separate link would probably make pip installing from the repo faster

**Comment by sheridana** [comment]
Yeah this has been bugging me recently too. This is because we opted to have all of the necessary post-processing scripts in the same package. I was thinking of moving to funlib.segment but not sure if it is the right fit. Maybe it makes most sense to have a lightweight `lsd_train` repo (just `lsd`) and move the post-processing scripts to an `lsd_post` repo. Or maybe creating a new funlib package that has common post-processing scripts (e.g watershed, agglomeration, etc) that are distinct from funlib.segment. @funkey do you have any thoughts on this? I agree though, this needs to be cleaned up and ideally published to pypi.

**Comment by pattonw** [comment]
I think keeping all of the lsd related stuff together in a single repo is good. If you want to separate stuff you can do it in here, just provide a `lsd.train`, and `lsd.post` submodules.
For ease of installation/use purposes, I think it is enough to just minimize the imports in `lsd/__init__.py`. You'd still throw the package not found errors, but only when someone tried to access the submodules/functions that require those packages, which I think is perfectly reasonable.

**Comment by sheridana** [comment]
@pattonw I merged restructure to main, so now you should just be able to use `lsd.train` for computing the shape descriptors. Also moved the tutorial checkpoint to be downloadable. Not sure about the pack file, but I don't think that's such a big deal. Not sure if it makes sense to have this on pypi anyway, maybe if the need arises in the future.

**Comment by pattonw** [comment]
:thumbsup: that sounds good. I still think it makes sense to publish on pypi so people can pip install. Its a bit annoying but pypi doesn't let you publish a package with github dependencies that automatically install meaning any library depending on lsd will have a 2 step install `pip install some-package`, `pip install git+https://github.com...`. Which is a lot for end users. I'd be happy to push a github action that will publish to pypi on a tagged commit

**Comment by sheridana** [comment]
Hmm okay that sounds good, thanks Will! Someone has the lsd name though right?

**Comment by pattonw** [comment]
Yes, I'm thinking use "lsds" for the package name?

**Comment by sheridana** [comment]
Oh haha yeah that's totally fine. Does pypi make it easy to handle the dependencies or do you think we should just keep these separate? For `lsd.train` this is not such a big deal, I think just gunpowder, scipy and numpy. But for `lsd.post` it gets a bit messy with the dependencies

**Comment by pattonw** [comment]
Yes, its handled pretty well. You can specify in the setup.py `install_requires=[...]`, and anything defined there will be installed automatically with your library (if this supported github links that would be ideal but apparently pypi doesn't want to automatically download and execute code from arbitrary links). It allows for versioning as well so you can request `gunpowder>1.2` etc.
I'll take a look and see if I can make a sensible publish script. I'm pretty sure you can separate your dependencies with features so someone could `pip install lsds` if they just want the basics, or `pip install lsds[post]` if they want the post dependencies as well.

**Comment by sheridana** [comment]
Oh yeah I remember now, was looking into that a while back. A publish script would be great!
